<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Load Script</title>
    <style>
        body {
            font-size: 30px
        }
    </style>
</head>

<body>

    <script>

        document.body.innerHTML = '';

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'Промисы' + "<br><br>"


        let promise = new Promise(function (resolve, reject) {
            // эта функция выполнится автоматически, при вызове new Promise
            // state: "pending", result: "undefined"


            resolve("done"); // state: "fulfilled", result: "done"

            reject(new Error("Whoops")); // игнорируется   // state: "rejected", result: "Whoops"
            // через 1 секунду сигнализировать, что задача выполнена с результатом "bla"
            setTimeout(() => resolve("bla")); // игнорируется // state: "fulfilled", result: "bla"

        });

        // Если мы заинтересованы только в результате успешного выполнения задачи, то в then можно передать только одну функцию
        // resolve запустит первую функцию, переданную в .then
        promise.then(
            result => console.log("111111111 " + result),
            error => console.log("111111111 " + error) // не будет запущена
        );

        promise.then(
            function (result) { console.log("22222222 " + result); /* обработает успешное выполнение */ },
            function (error) { console.log("22222222 " + error)/* обработает ошибку */ }
        );



        // Если мы хотели бы только обработать ошибку, то можно использовать null в качестве первого аргумента: .then(null, errorHandlingFunction). 
        // Или можно воспользоваться методом .catch(errorHandlingFunction), который сделает то же самое
        let promise2 = new Promise((resolve, reject) => {
            setTimeout(() => reject(new Error("33333333 Ошибка!")), 1000);
        });

        // .catch(f) это то же самое, что promise.then(null, f)
        promise2.catch(console.log); // выведет "Error: Ошибка!" спустя одну секунду


        //////////
        // Вызов .finally(f) похож на .then(f, f), в том смысле, что f выполнится в любом случае, когда промис завершится: успешно или с ошибкой
        // finally(f) – это не совсем псевдоним then(f,f), как можно было подумать
        // 1. Обработчик, вызываемый из finally, не имеет аргументов
        // 2. Обработчик finally «пропускает» результат или ошибку дальше, к последующим обработчикам

        new Promise((resolve, reject) => {
            setTimeout(() => resolve("value"), 2000);
        })
            .finally(() => console.log("44444444 Промис завершён")) // срабатывает первым
            .then(result => console.log("44444444 " + result)); // <-- .then показывает "value"

        new Promise((resolve, reject) => {
            throw new Error("error");
        })
            .finally(() => console.log("44444444 Промис завершён")) // срабатывает первым
            .catch(err => console.log("44444444 " + err));  // <-- .catch показывает ошибку

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'Пример: loadScript' + "<br><br>"

        // У нас есть функция loadScript для загрузки скрипта из предыдущей главы
        // Новой функции loadScript более не нужен аргумент callback

        function loadScript(src) {
            return new Promise(function (resolve, reject) {
                let script = document.createElement('script');
                script.src = src;

                script.onload = () => resolve(script);
                script.onerror = () => reject(new Error(`Ошибка загрузки скрипта ${src}`));

                document.head.append(script);
            });
        }


        let promise3 = loadScript("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js");

        promise3.then(
            script => console.log(`55555555 ${script.src} загружен!`),
            error => console.log(`55555555 Ошибка: ${error.message}`)
        );

        promise3.then(script => console.log('55555555 Ещё один обработчик...'));


        console.log("=================");

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'Цепочка промисов' + "<br><br>"

        new Promise(function (resolve, reject) {

            setTimeout(() => resolve(1), 1000); // (*)

        }).then(function (result) { // (**)

            console.log('66666666 ' + result); // 1
            return result * 2;

        }).then(function (result) { // (***)

            console.log('66666666 ' + result); // 2
            return result * 2;

        }).then(function (result) {

            console.log('66666666 ' + result); // 4
            return result * 2;

        });

        console.log("=================");

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'Возвращаем промисы' + "<br><br>"

        // Обработчик handler, переданный в .then(handler), может вернуть промис
        // В этом случае дальнейшие обработчики ожидают, пока он выполнится, и затем получают его результат

        new Promise(function (resolve, reject) {

            setTimeout(() => resolve(1), 1000);

        }).then(function (result) {

            console.log('77777777 ' + result); // 1

            return new Promise((resolve, reject) => { // (*)
                setTimeout(() => resolve(result * 2), 1000);
            });

        }).then(function (result) { // (**)

            console.log('77777777 ' + result); // 2

            return new Promise((resolve, reject) => {
                setTimeout(() => resolve(result * 2), 1000);
            });

        }).then(function (result) {

            console.log('77777777 ' + result); // 4

        });

        console.log("=================");

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'Возвращаем промисы Пример: loadScript' + "<br><br>"

        // loadScript with promise defined above in this script
        loadScript("loadedScript.js")
            .then(function (script) {
                return loadScript("loadedScript.js");
            })
            .then(function (script) {
                return loadScript("loadedScript.js");
            })
            .then(function (script) {
                // вызовем функции, объявленные в загружаемых скриптах,
                // чтобы показать, что они действительно загрузились
                one();
                two();
                three();
            });

        // // Этот же код можно переписать немного компактнее, используя стрелочные функции:
        // loadScript("loadedScript.js")
        //     .then(script => loadScript("loadedScript.js"))
        //     .then(script => loadScript("loadedScript.js"))
        //     .then(script => {
        //         // скрипты загружены, мы можем использовать объявленные в них функции
        //         one();
        //         two();
        //         three();
        //     });

        // // Технически мы бы могли добавлять .then напрямую к каждому вызову loadScript, вот так:
        // loadScript("/article/promise-chaining/one.js").then(script1 => {
        //     loadScript("/article/promise-chaining/two.js").then(script2 => {
        //         loadScript("/article/promise-chaining/three.js").then(script3 => {
        //             // эта функция имеет доступ к переменным script1, script2 и script3
        //             one();
        //             two();
        //             three();
        //         });
        //     });
        // });
        // // Этот код делает то же самое: последовательно загружает 3 скрипта. Но он «растёт вправо», так что возникает такая же проблема, как и с колбэками.

        console.log("=================");

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'Thenable' + "<br><br>"

        // Если быть более точными, обработчик может возвращать не именно промис, а любой объект, содержащий метод .then, такие объекты называют «thenable»
        // Вот пример такого объекта:
        class Thenable {
            constructor(num) {
                this.num = num;
            }
            then(resolve, reject) {
                console.log('88888888 ' + resolve); // function() { native code }
                // будет успешно выполнено с аргументом this.num*2 через 1 секунду
                setTimeout(() => resolve('88888888 ' + (this.num * 2)), 1000); // (**)
            }
        }

        new Promise(resolve => resolve(1))
            .then(result => {
                return new Thenable(result); // (*)
            })
            .then(console.log); // показывает 2 через 1000мс

        console.log("=================");

        ////////////////////////////////////////////////////////////////////////////////////

        document.body.innerHTML += 'TODO: Более сложный пример: fetch' + "<br><br>"
        document.body.innerHTML += 'TODO: Промисы: обработка ошибок' + "<br><br>"
        document.body.innerHTML += 'TODO: Promise API' + "<br><br>"
        document.body.innerHTML += 'TODO: Промисификация' + "<br><br>"
        document.body.innerHTML += 'TODO: Микрозадачи' + "<br><br>"


    </script>

    <br>
    <a href="../../index.html">home</a>

</body>

</html>